### ISSUE TITLE
Add async version

### ISSUE THREAD

**Issue by AzSiAz** [gh123man/Refresher#1]
Like iOS 15 refreshable, using an Async action would prevent having to handle done callback and pass it to function call

**Comment by gh123man** [comment]
Thanks for the feedback! I'll look into adding this.

**Comment by gh123man** [comment]
Done! https://github.com/gh123man/SwiftUI-Refresher/commit/d54b29f3ac918cbf86e06b7ed367d911825510c5
[1.0.8](https://github.com/gh123man/SwiftUI-Refresher/releases/tag/1.0.8)

**Comment by AzSiAz** [comment]
Fantastic, thank you 😊
