### ISSUE TITLE
VisionOS Support

### ISSUE THREAD

**Issue by yasircb** [gh123man/Refresher#12]
I would like to be able to run my app on VisionOS, but it's missing support in Package.swift (Swift Package Manager).

**Comment by gh123man** [comment]
Hi, Ive added package support here https://github.com/gh123man/SwiftUI-Refresher/commit/9e1948c6597ef890f51edfe8279601718763c7b8

Please let me know if it works. I have not tested it.

**Comment by yasircb** [comment]
@gh123man Thanks for adding support for visionOS. I verified on visionOS and it works fine. Just below line of code is not available in visionOS target.
`UIImpactFeedbackGenerator(style: .medium).impactOccurred()`

**Comment by gh123man** [comment]
If there is an error, could you open a PR with the appropriate `#if available` (I am not currently testing VisionOS), or if it is not a blocker, ill close this issue. Thanks!
