### ISSUE TITLE
Can we change the spinner foreground color?

### ISSUE THREAD

**Issue by devmuz** [gh123man/Refresher#28]

**Comment by gh123man** [comment]
👋 Hi

The spinner can be fully customized.[ See the example in the readme](https://github.com/gh123man/SwiftUI-Refresher?tab=readme-ov-file#customization)

You can supply a different view to use as the spinner for each state. Here you can supply a different color. 
We don't expose the ability to directly customize the default spinner - but it's [implementation is fairly simple](https://github.com/gh123man/SwiftUI-Refresher/blob/master/Sources/Refresher/DefaultRefreshView.swift#L24). You can copy that into your project and customize it as needed.

**Comment by devmuz** [comment]
Okay Thanks! I fixed this by copying the code to use my own AppRefreshView and done the changes in ActivityView to update the UIActivityIndicatorView color.
